apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: mlops-lib
spec:
  templates:
    # --- TRAIN ---
    - name: train-model-tmpl
      inputs:
        parameters:
          - name: repo-url
          - name: model-name
      container:
        image: ghcr.io/atkaridarshan04/ml-trainer:v1.0.0
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: s3creds
        env:
          - name: MLFLOW_TRACKING_URI
            value: http://mlflow.mlflow.svc.cluster.local:5000
          - name: DATA_URI
            value: data/raw/housing.csv
        command: ["/bin/bash", "-c"]
        args:
          - |
            set -e
            git clone {{inputs.parameters.repo-url}} repo && cd repo

            dvc pull data/raw/housing.csv
            python -m pipelines.train

            MODEL_VERSION=$(python - <<'EOF'
            import mlflow
            from mlflow.tracking import MlflowClient
            client = MlflowClient("http://mlflow.mlflow.svc.cluster.local:5000")
            latest = client.get_latest_versions("{{inputs.parameters.model-name}}", stages=[])
            print(latest[-1].version)
            EOF
            )

            echo -n "$MODEL_VERSION" > /tmp/model_version.txt
      outputs:
        parameters:
          - name: model-version
            valueFrom:
              path: /tmp/model_version.txt

    # --- PROMOTE ---
    - name: promote-model-tmpl
      inputs:
        parameters:
          - name: model-version
          - name: model-name
      container:
        image: ghcr.io/atkaridarshan04/mlflow-server:v3.8.0
        env:
          - name: MODEL_VERSION
            value: "{{inputs.parameters.model-version}}"
          - name: MODEL_NAME
            value: "{{inputs.parameters.model-name}}"
          - name: MLFLOW_TRACKING_URI
            value: http://mlflow.mlflow.svc.cluster.local:5000
        command: ["python", "-c"]
        args:
          - |
            import os
            from mlflow.tracking import MlflowClient
            version = int(os.environ["MODEL_VERSION"].strip())
            client = MlflowClient(os.environ["MLFLOW_TRACKING_URI"])
            client.set_registered_model_alias(name=os.environ["MODEL_NAME"], alias="production", version=version)

    # --- RESOLVE ---
    - name: resolve-uri-tmpl
      inputs:
        parameters:
          - name: model-name
      container:
        image: python:3.10
        command: ["sh", "-c"]
        args:
          - |
            pip install mlflow -q
            python -c '
            from mlflow.tracking import MlflowClient
            client = MlflowClient("http://mlflow.mlflow.svc.cluster.local:5000")
            mv = client.get_model_version_by_alias("{{inputs.parameters.model-name}}", "production")
            uri = client.get_model_version_download_uri("{{inputs.parameters.model-name}}", mv.version)
            with open("/tmp/model_uri.txt", "w") as f: f.write(uri)
            '
      outputs:
        parameters:
          - name: model-uri
            valueFrom:
              path: /tmp/model_uri.txt

    # --- UPDATE GIT ---
    - name: update-git-tmpl
      inputs:
        parameters:
          - name: repo-url
          - name: model-uri
          - name: manifest-path
      container:
        image: alpine/git
        env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-token
              key: token
        command: ["sh", "-c"]
        args:
          - |
            set -e
            AUTH_URL=$(echo "{{inputs.parameters.repo-url}}" | sed "s|https://|https://x-access-token:${GITHUB_TOKEN}@|")
            git clone $AUTH_URL repo && cd repo
            sed -i "s|storageUri:.*|storageUri: \"{{inputs.parameters.model-uri}}\"|" {{inputs.parameters.manifest-path}}
            git config user.email "ci@mlops.local"
            git config user.name "mlops-ci"
            git add .
            git commit -m "chore: update production model uri"
            git push origin main