apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: housing-ci-pipeline-
spec:
  entrypoint: mlops-pipeline
  serviceAccountName: s3-sa

  arguments:
    parameters:
      - name: model-name
        value: CaliforniaHousingRegressor
      - name: repo-url
        value: https://github.com/atkaridarshan04/ml-from-scratch-to-prod.git
      - name: manifest-path
        value: k8s/workloads/inference-service.yml

  templates:
  - name: mlops-pipeline
    steps:
      - - name: train
          templateRef:
            name: mlops-lib
            template: train-model-tmpl
          arguments:
            parameters:
              - name: repo-url
                value: "{{workflow.parameters.repo-url}}"
              - name: model-name
                value: "{{workflow.parameters.model-name}}"

      - - name: promote
          templateRef:
            name: mlops-lib
            template: promote-model-tmpl
          arguments:
            parameters:
              - name: model-version
                value: "{{steps.train.outputs.parameters.model-version}}"
              - name: model-name
                value: "{{workflow.parameters.model-name}}"

      - - name: resolve-uri
          templateRef:
            name: mlops-lib
            template: resolve-uri-tmpl
          arguments:
            parameters:
              - name: model-name
                value: "{{workflow.parameters.model-name}}"

      - - name: update-git
          templateRef:
            name: mlops-lib
            template: update-git-tmpl
          arguments:
            parameters:
              - name: repo-url
                value: "{{workflow.parameters.repo-url}}"
              - name: model-uri
                value: "{{steps.resolve-uri.outputs.parameters.model-uri}}"
              - name: manifest-path
                value: "{{workflow.parameters.manifest-path}}"